### PR TITLE
Campaigns are maps

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

I find easier and more logical to categorize campaigns as maps rather than "other".

### CODE REVIEW

**Comment by misiokles** [comment]
Yeah, now it's better!

**Comment by Fabrice-TIERCELIN** [comment]
I have tested one HotA campaign. It starts with a prolog but I fail to retrieve it in the mod. Where is it? Is it possible to create a video and play it as a prolog or an epilog in a custom campaign?

**Comment by Olegmods** [comment]
> I have tested one HotA campaign. It starts with a prolog but I fail to retrieve it in the mod. Where is it? Is it possible to create a video and play it as a prolog or an epilog in a custom campaign?

It will require to convert the campaign to VCMP format to add custom video to the campaign.

**Comment by Fabrice-TIERCELIN** [comment]
How to create/convert a campaign in _VCMI_ format, @Olegmods?

**Comment by misiokles** [comment]
https://vcmi.eu/modders/Campaign_Format/

**Pull request merged**
